### ISSUE TITLE
为什么更新了全都是这个节点45.137.97.205

### ISSUE THREAD

**Issue by KrysMs1** [mianfeifq/share#3]
而且去除重复服务器选项 [因为传输协议不一样也没办法成功的去重]  实际上服务器是一样的 测速都是 远程服务器返回错误503
![QQ拼音截图20220717141531](https://user-images.githubusercontent.com/40438583/179386526-976ebb0b-614d-47ee-ac7d-1072214e8c62.png)

**Comment by KrysMs1** [comment]
目测大概有十分之一是这个服务器 重复测速相同节点实在有点想吐槽 还是感谢作者的发电

**Comment by mianfeifq** [comment]
45.137.97.205每个Trojan节点的密码都不一样，不是重复节点
节点实际是可以用的

**Comment by kongkongNG** [comment]
我的这个节点用不了欸。。
此外，使用 Lite Speedtest有许多高速节点，在测试真链接延迟时都发现用不了，连接后会有下面报错：
app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > proxy/trojan: failed to flush payload > tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
请问是什么原因呢？是服务器不给使用吗。。
