### ISSUE TITLE
库

### ISSUE THREAD

**Issue by mo479022490** [mianfeifq/share#5]
我的储存库怎么有你的库？

**Comment by mianfeifq** [comment]
不清楚你具体有什么问题

**Comment by mo479022490** [comment]
![IMG_20221116_180003.jpg](https://user-images.githubusercontent.com/64945061/202150282-bd2ab5e2-cc4c-4f0f-8d54-2df853d19a4a.jpg)![IMG_20221116_175731.jpg](https://user-images.githubusercontent.com/64945061/202150323-62c7b1bd-27eb-4096-a0ff-004bebe69fa5.jpg)储存库里有你的库，然后我什么都不能收藏了！
