### ISSUE TITLE
servers are not updated through the link

### ISSUE THREAD

**Issue by AbadanVpn** [mianfeifq/share#7]
Unfortunately, when I try to update through the link, the servers are not updated. After checking your page, I realized that you have updated the servers, but they are not updated through the link.

**Comment by mianfeifq** [comment]
the link will be changed on the first day of every month, so use the latest link from the readme page.

**Comment by mianfeifq** [comment]
https://github.com/mianfeifq/share/blob/main/data2023025.txt

https://raw.githubusercontent.com/mianfeifq/share/main/data2023025.txt

the content inside the two files are different, i don't know why.

**Comment by mianfeifq** [comment]
you can use gitlab link: [https://gitlab.com/mianfeifq/share/-/raw/master/data2023025.txt](https://gitlab.com/mianfeifq/share/-/raw/master/data2023025.txt)

**Comment by AbadanVpn** [comment]
> you can use gitlab link: https://gitlab.com/mianfeifq/share/-/raw/master/data2023025.txt

Thank you
